CREATE TABLE IF NOT EXISTS news (
  id SERIAL PRIMARY KEY,
  date TIMESTAMP NOT NULL, 
  title VARCHAR NOT NULL,
  url VARCHAR NULL,
  text VARCHAR NOT NULL
);

ALTER TABLE news ADD UNIQUE (date, url);